# Generated by Django 6.1 on 2026-08-31 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendada', models.DateField(verbose_name='Data Agendada')),
                ('horario_da_daily', models.TimeField(blank=True, null=True, verbose_name='Horário da Daily')),
                ('link_reuniao', models.URLField(max_length=1000, verbose_name='Link da Chamada')),
                ('resumo_pauta', models.TextField(blank=True, null=True, verbose_name='Pauta / Resumo')),
                ('organizador_da_daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailies_agendadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-horario_da_daily'],
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('estagiario', 'Estagiário'), ('junior', 'Júnior'), ('senior', 'Sênior'), ('chefe', 'Chefe de Setor')], default='junior', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feito_ontem', models.TextField(blank=True, null=True, verbose_name='Feito Ontem')),
                ('planejamento_hoje', models.TextField(blank=True, null=True, verbose_name='Planejamento de Hoje')),
                ('impedimentos', models.TextField(blank=True, null=True, verbose_name='Impedimentos')),
                ('daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='TASK_SETORES.daily_meeting')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_notas', to='TASK_SETORES.membro')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data Criação')),
                ('membros', models.ManyToManyField(related_name='Setores', through='TASK_SETORES.Membro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='membro',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TASK_SETORES.setor'),
        ),
        migrations.AddField(
            model_name='daily_meeting',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailies', to='TASK_SETORES.setor'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('a fazer', 'A Fazer'), ('em processo', 'Em Processo'), ('concluido', 'Concluido')], default='a fazer', max_length=20)),
                ('prioridade', models.CharField(choices=[('relevante', 'Relevante'), ('mediana', 'Mediana'), ('extrema', 'Extrema')], default='relevante', max_length=20)),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_atribuidas', to='TASK_SETORES.membro')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_criadas', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='TASK_SETORES.setor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='membro',
            unique_together={('usuario', 'setor')},
        ),
    ]
