# Generated by Django 6.1 on 2026-09-01 03:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data Criação')),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendada', models.DateField(verbose_name='Data Agendada')),
                ('horario_da_daily', models.TimeField(blank=True, null=True, verbose_name='Horário da Daily')),
                ('link_reuniao', models.URLField(max_length=1000, verbose_name='Link da Chamada')),
                ('resumo_pauta', models.TextField(blank=True, null=True, verbose_name='Pauta / Resumo')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailies', to='TASK_SETORES.setor')),
            ],
            options={
                'ordering': ['-horario_da_daily'],
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cargo', models.CharField(choices=[('estagiario', 'Estagiário'), ('junior', 'Júnior'), ('senior', 'Sênior'), ('chefe', 'Chefe de Setor')], default='junior', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='TASK_SETORES.setor')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('a fazer', 'A Fazer'), ('em processo', 'Em Processo'), ('concluido', 'Concluido')], default='a fazer', max_length=20)),
                ('prioridade', models.CharField(choices=[('relevante', 'Relevante'), ('mediana', 'Mediana'), ('extrema', 'Extrema')], default='relevante', max_length=20)),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='TASK_SETORES.setor')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_atribuidas', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feito_ontem', models.TextField(blank=True, null=True, verbose_name='Feito Ontem')),
                ('planejamento_hoje', models.TextField(blank=True, null=True, verbose_name='Planejamento de Hoje')),
                ('impedimentos', models.TextField(blank=True, null=True, verbose_name='Impedimentos')),
                ('daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='TASK_SETORES.daily_meeting')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_notas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='daily_meeting',
            name='organizador_da_daily',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailies_agendadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
