# Generated by Django 6.1 on 2026-08-31 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TASK_SETORES', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_criadas', to='TASK_SETORES.membro'),
        ),
    ]
